#!/bin/bash
echo "Зайти в папку"
cd group_26
echo "Создать три папки"
mkdir p1 p2 p3
echo "Зайти в любую папку"
cd p1
echo "Создать 5 файлов"
touch 1.txt 2.txt 3.txt 1.json 2.json
echo "Создать три папки"
mkdir w1 w2 w3
echo "Вывести содержимое папки"
ls -la
echo "Переместить любые 2 файла, которые вы создали, в любую другую папку"
mv 1.json 1.txt w1/
